name: ${project.name}
description: Some EULA friendly perks.
author: BenCodez
version: ${project.version}
main: com.bencodez.mcperks.MCPerksMain
softdepend: [VotingPlugin]
api-version: 1.13
libraries:
  - org.openjdk.nashorn:nashorn-core:15.2
commands:
  mcperks:
    description: MCPerks commands
    aliases: [mcp, perks]
  mcperksreload:
    description: MCPerks commands
  mcperkshelp:
    description: MCPerks commands
permissions:
  MCPerks.AllPerks:
    description: Permission for all perks