# Config.yml
# Welcome to MCPerks!
# Perks are located in Perks folder
# Permissions are mcperks.(filename) - filename without extenstion

# Debug levels:
# NONE
# INFO
# EXTRA
DebugLevel: NONE

# Valid Options:
# - SQLITE
# - MYSQL
DataStorage: SQLITE

# Log perks being activated
LogActivation: false

# Whether or not to create daily backups. (Only the most recent ones get saved)
CreateBackups: false

# Information for mysql
MySQL:
  Host: ''
  # Default port is 3306
  Port: 3306 
  Database: ''
  Username: ''
  Password: ''
  # Max number of connections
  MaxConnections: 1

# Wether or not to load command aliases
LoadCommandAliases: true

# If true only one perk can be activated at a time
# If false, unlimited number of perks can be activated at a time
PerkQue: true

# If true, players can only see perks in /mcperks 
# they have permission to
# Default is True
RequirePermToView: true

# If true, GUI will stay open after activating a perk
KeepGUIOpen: false

# Load default perks
LoadDefaultPerks: true

# Valid options
# - ALL
# - PLAYER
# - TOWNY
# - FACTIONS
# - PERMISSION
PerkSystemType: 'ALL'

# Permission if perksystemtype is permission
PerkSystemTypePermission: "Permission here"

# If true, reactivating a perk will deactivate
DisableOnClick: false

# Deactivate perk on logout
DeactivateOnLogout: false

# Enable if certain modifiers don't get removed
ForceClearModifiers: false

# List of disabled worlds on a global level
# Does not work on all effects
# Per perk options available
DisabledWorlds: []

#PerkGUIExtraItems:
#  Item1: 
#    Material: STONE
#    Amount: 1
#    FillSlots:
#    - 0
#    - 1
#    - 2
#    - 3
#    - 4
#    - 5
#    - 6
#    - 7
#    - 8

# Global perk options
# Add the following in any perk fine to override these

# At how many seconds left a count should be broadcasted
CountDownTimes:
- '10'
- '3'
- '2'
- '1'

# Count down bossbar
BossBar:
  Enabled: false
  # Message to send
  # Use %minutes% for minutes
  Message: '&a%perk% ends in %seconds% seconds'
  # Bar Colors:
  # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarColor.html
  Color: 'BLUE'
  # Bar Styles:
  # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarStyle.html
  Style: 'SOLID'
  # Hide bossbar after 15 seconds
  #HideInDelay: 15

  
# CountDown, activation, and deactivation can have mutiple different effects
# They execute reward files, see here what can be done:
# https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards
# https://github.com/Ben12345rocks/AdvancedCore/wiki/Reward-files
CountDownEffect:
  Firework:
    Enabled: false
    Power: 2
    # Colors can be found here:
    # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/DyeColor.html
    Colors:
    - BLUE
    FadeOutColor: 
    - RED
    Trail: true
    Flicker: true
    # Types can be found here:
    # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/FireworkEffect.Type.html
    Types:
    - BALL_LARGE
    
ActivationEffect:
  Firework:
    Enabled: false
    Power: 2
    # Colors can be found here:
    # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/DyeColor.html
    Colors:
    - BLUE
    FadeOutColor: 
    - RED
    Trail: true
    Flicker: true
    # Types can be found here:
    # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/FireworkEffect.Type.html
    Types:
    - BALL_LARGE
    
DeactivationEffect:
  Firework:
    Enabled: false
    Power: 2
    # Colors can be found here:
    # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/DyeColor.html
    Colors:
    - BLUE
    FadeOutColor: 
    - RED
    Trail: true
    Flicker: true
    # Types can be found here:
    # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/FireworkEffect.Type.html
    Types:
    - BALL_LARGE
    
# Give user MCPerks.Limit.1 to only have 1 active perk at a time
LimitPermission: false

# If true, players need to be given an activation 
LimitActivations: false

# Allow same perks to be active 
DuplicatePerksActive: false

# Default Item lore
# Can also put this in each perk file
# to define specific messages for each perk in gui
# PlaceHolders:
# %Description% - Perk description
# %HasPerm% - True/False
# %CoolDownLeft% - Seconds left until cooldown over
# %CoolDown% - Perk cooldown
Lore:
  Available: 
  - '&aClick to activate perk'
  - '&aCoolDown:  %CoolDown%'
  - '&aDescription: %Description%'
  Active: 
  - '&aCurrently active'
  - '&aTimeLeft: %TimeLeft%'
  InCoolDown: 
  - '&aCoolDownLeft: %CoolDownLeft%'
  LimitReached: 
  - '&aPerk limit reached'
  
# Data is saved in ServerData.yml
StorePerkHistory: false

# Enable Geyser prefix support
GeyserPrefixSupport: false
GeyserPrefix: '*'